telegram:
  token: 673427571:AAH-cloRb3vAimtFrOolg2cQdxCGwio9O9M      # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  token: NTI2MTk5MzA1MDgyNzY1MzYy.DwBtDg.NaBwRS4qdla3w49HH9dg5MIKHDo       # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
bridges:
  - name: Default bridge
    direction: both
    telegram:
      chatId: -1001110770633  # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
    discord:
      serverId: '267070171930165258'         # This ID must be wrapped in single quotes. Example: '244791815503347712'
      channelId: '526206227370344450'       # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
debug: false
